### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by in3rsha** [sr-gi/bitcoin_tools#17]
Hello there. I am trying to dump the UTXOs using the example code in the README.md:

```
from bitcoin_tools.analysis.status.data_dump import utxo_dump
from bitcoin_tools.analysis.status.utils import parse_ldb

# Set the version of the Bitcoin Core you are using (which defines the chainstate format)
# and the IO files.

f_utxos = "decoded_utxos.txt"
f_parsed_utxos = "parsed_utxos.txt"

# Parse all the data in the chainstate.
parse_ldb(f_utxos)
# Parses transactions and utxos from the dumped data.
utxo_dump(f_utxos, f_parsed_utxos)

# Data is stored in f_utxos and f_parsed_utxos files respectively
```
When it gets to the `utxo_dump()` function, the script exits with the following error:

```
Traceback (most recent call last):
  File "utxodump.py", line 14, in <module>
    utxo_dump(f_utxos, f_parsed_utxos, "bitcoin")
  File "/usr/lib/python2.7/bitcoin_tools/analysis/status/data_dump.py", line 101, in utxo_dump
    raw_np = out["amount"] / float(min_size)
ZeroDivisionError: float division by zero
```

I've been able to get around this by hard-coding this in `data_dump.py` to try and avoid an error:

```
# min_size = get_min_input_size(out, utxo["height"], count_p2sh, coin)
min_size = 0.00000001 # my edit
```

This is just a hack though, and was wondering if there was another reason why I might be getting this error?

**Comment by sr-gi** [comment]
Looks like you found a bug!

### Issue
`min_size` is returning `0` since `count_p2sh` (whether to take P2SH into account or not) is set to `False`, so `get_min_input_size` is not accounting for P2SH scripts.

The logic of `get_min_size` is to set min_size to 0 when `count_p2sh` is set to `False`, but such behavior is not handled `in utxo_dump` (it was accidentally removed in [here](https://github.com/sr-gi/bitcoin_tools/commit/2bfd84f900fd3ffe2d5181b4786195f3c4510186#diff-e0919382722d051b2323a1c69ef33ed3L112))

Looks like it passed unnoticed since we always run analysis taking P2SH into account.

### Solution

Run it with `count_p2sh = True`

PS: Looks like the README example was also outdated since `coin` is also missing.

**Comment by in3rsha** [comment]
Thank you. Also, thank you for your paper and for making this tool available. It's the only tool I know of that allows you to get a workable list of the bitcoin utxo set.

**Comment by sr-gi** [comment]
Glad you like it. I've fixed the issue in the last commit.

Feel free to drop any other comment / issue you may find.
